---
title: "Research Output"
---

#### Publications & Conference Proceedings

- Abburu, A., Agarwal, S., & Mukherjee, S. (accepted). Heterogeneity in Loss Aversion Estimates across Modeling Approaches. Proceedings of the Annual Meeting of the Cognitive Science Society. | **Talk**
- Abburu, A., & Mukherjee, S. (2024). Cognitive Science is (largely) Psychological Science. Proceedings of the Annual Meeting of the Cognitive Science Society, 46(0). [link](https://escholarship.org/uc/item/0m78k9jj) |  Poster

#### Presentations

- Abburu, A. (2024, December). LLMs and Ethical Dilemmas: Would AI push you off a boat to save five people? Annual Conference of Cognitive Science 11, Indian Institute of Technology Bombay (IITB). | Poster
- Abburu, A., Agarwal, S., & Mukherjee, S. (2024a). Loss Aversion: Insights from Diverse Estimation Approaches. 2024 Indian Judgment and Decision Making Conference, Indian Institute of Technology (IIT) Mandi. | Talk
- Abburu, A., Agarwal, S., & Mukherjee, S. (2024b, December). Heterogeneity in Loss Aversion Estimates across Modeling Approaches. Annual Conference of Cognitive Science 11, Indian Institute of Technology Bombay (IITB). | Poster
- Singh, P., Ramanathan, P., & Abburu, A. (2023, August 31). Trends in Applied Social Psychology Research across Regions. Symposium on Cross-cultural and Applied Psychology, 27th Regional European Conference of the International Association for Cross-Cultural Psychology, Limerick, Ireland. | Talk
- Abburu, A., & Mukherjee, S. (2022). Top Trends and Topics in JDM: A Bibliometric analysis of the journal Judgment and Decision Making (2008-2021) (Accepted, but not presented). SJDM 2022, San Diego. | Poster
- Abburu, A., Roy, S., Zena, L., Indumathy, J., & Kanth, B. (2021). Investigating Loss of Face and Psychological Distress using Self-Construals. Annual Convention of the National Academy of Psychology. | Talk

