---
title: Student bodies of IIT Delhi
draft: false
---

### I. Institute Level

**Student Affairs Council (SAC)**

-   *Administrative Members*
    -   Director
    -   Dean of Students
    -   Deputy Directors
    -   Dean, Academics & Associate Deans of Student Affairs
    -   Two nominees of the Senate
    -   One Housemaster
    -   Assistant Registrar (Student Affairs) or other Administrative Officer
    -   Two Wardens
    -   Immediate past Dean of Students
    -   Head, Counseling Services
-   *Student Representatives*
    -   General Secretary, Student Affairs
    -   Deputy General Secretary, Student Affairs
    -   General Secretaries of student boards recognized by S.A.C
    -   General Secretary of C.A.I.C
    -   Immediate past two General Secretaries, Student Affairs
    -   One representative from each hostel (except the married students hostel)
    -   Two representatives of the married students' hostel
        -   One each for apartments (IP & Nalanda) and A-type flats
    -   Research Scholars Representatives (10)
        -   Residing inside campus (4)
        -   Residing outside campus (6)
    -   M.Tech. Representatives (2)
    -   M.Sc. Representative (1)
    -   P.G. Programs Representative (1) (DIIT, M.Des, MSR, MBA)
    -   Day Scholars Representative (1) (All UG/PG Students not residing in hostels)
    -   Representative Married Students' Hostel 1 from 'A' type quarters
	-   Representative from Indradhanu
    -   SwD Representative (1) (All UG/PG)
    -   Secretaries of the committees set up by the S.A.C.
    -   Immediate past General Secretaries of the Boards recognized by the S.A.C.
    -   Two representatives from CAIC
    -   Web and Design Nominees
        -   The General Secretary, S.A.C can nominate 1 Web and 1 Design Executive student member

**Co-curricular and Academic Interaction Council (CAIC)**
(non-functional website)

### II. Boards and Committees under SAC

**Board for Hostel Management (BHM)**

-   President, B.H.M.
-   Associate Dean Hostel Management
-   All Wardens
-   Deputy/Assistant Registrar (S.A.) or other administrative personnel
-   General Secretary, B.H.M.
-   Deputy General Secretary, Maintenance Affairs
-   Deputy General Secretary, Mess Affairs
-   All House Secretaries
-   All Mess Secretaries
-   All Maintenance Secretaries
-   Secretaries, B.H.M.
-   Representatives, B.H.M.
-   Immediate past General Secretary, B.H.M. (permanent invitee)

**Board for Student Welfare (BSW)**

-   President, B.S.W (Ex officio, Associate dean, Welfare)
-   Vice-President, B.S.W
-   General Secretary, B.S.W.
-   Deputy General Secretary (Operations)
-   Deputy General Secretary (Mentor)
-   Immediate past President, B.S.W. (Ex officio, if the incumbent is still a faculty member)
-   General Secretary, S.A.C. (Ex officio)
-   Two elected representatives of each hostel (except Nalanda Hostel)
-   Mentorship Committee (MRC)
-   Finance Secretary
-   Public Relation Secretary
-   Immediate past General Secretary, B.S.W. (Ex officio, if the incumbent is still a bona fide student of the Institute)
-   Counsellor
-   Advisers of S.C. /S.T. and foreign students

**Board for Sports Activities (BSA)**

-   President, B.S.A.
-   Vice-President, B.S.A.
-   Game/Club Presidents
-   All Institute Team Captains
-   All Institute Team Vice-Captains
-   All Club Secretaries
-   All Sports Officers
-   Hostel Sports Secretary
-   General Secretary, Sports
-   Deputy General Secretary, Sports
-   Immediate past General Secretary, Sports
-   The immediate past President, B.S.A. (permanent invitee)

**Board for Recreational and Creative Activities (BRCA)**

-   President, B.R.C.A.
-   General Secretary, B.R.C.A.
-   Vice President, B.R.C.A.
-   Dy. General Secretary
-   Assistant Registrar (Student Affairs)/other administrative officer
-   Presidents of Activities
-   Secretaries of Activities

**Board for Student Publications (BSP)**

-   President, B.S.P.
-   Vice-President, B.S.P.
-   General Secretary, B.S.P.
-   Dy. General Secretary
-   Web Chief Editor (1)
-   Media Chief Editor (1)
-   Design Chief Editors (2)
-   Creative Writing & Outreach Chief Editors (2 – one each for English and Hindi)
-   Journalism Chief Editors (4)
-   Technical Editors (12)
-   Journalists (18)
-   General Secretary, SAC
-   Immediate past General Secretary, Board for Student Publications
-   Immediate past President, B.S.P.

### III. Hostel Level

**For each hostel:**

-   House Secretary (1 post)
-   Mess Secretary (1 post)
-   Sports Secretary (1 post)
-   Cultural Secretary (1 post)
-   Maintenance Secretary (1 post)
-   Other Secretaries as per individual hostels' HWC decision/past practice
-   Class Representatives to HWC
-   Secretary to SAC (1 post)
-   Representative to BHM (1 post)
-   Representative to BSW (2 posts)
-   Representative to BRCA (each club 1 post)
-   Dance Club Representative
-   Dramatics Club Representative
-   Debating Club Representative
-   Quizzing Club Representative
-   Music Club Representative
-   Literary Club Representative
-   Fine Arts & Crafts Representative
-   Photography & Film Representative
-   Hindi Samiti Representative
-   SPICMACAY Representative
-   Design Representative
-   Representative to Indoor Sports Club (ISC) (1 post)

**Committees under HWC:**

-   Mess Committee
-   Common Room Committee
-   House Honors Committee
-   House Maintenance & Cleanliness Committee
-   Computer Users Committee
